// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3hyUzpTKm1MkyjlIudOin16PDQGuJdAU',
    appId: '1:584375209306:web:87868c3ba7bf9f8a907763',
    messagingSenderId: '584375209306',
    projectId: 'elderly-care-2d133',
    authDomain: 'elderly-care-2d133.firebaseapp.com',
    storageBucket: 'elderly-care-2d133.appspot.com',
    measurementId: 'G-2DFDKK3P56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_GMjy0Q6s9Gj3Pai5spLoEfMR77jB_ew',
    appId: '1:584375209306:android:c04235de2d042ace907763',
    messagingSenderId: '584375209306',
    projectId: 'elderly-care-2d133',
    storageBucket: 'elderly-care-2d133.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3hyUzpTKm1MkyjlIudOin16PDQGuJdAU',
    appId: '1:584375209306:web:fc0cf8d6e1bcb068907763',
    messagingSenderId: '584375209306',
    projectId: 'elderly-care-2d133',
    authDomain: 'elderly-care-2d133.firebaseapp.com',
    storageBucket: 'elderly-care-2d133.appspot.com',
    measurementId: 'G-EE44FQV3W8',
  );
}
